
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyczqgeyhjxwfyjgwmio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Y3pxZ2V5aGp4d2Z5amd3bWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjczNjAsImV4cCI6MjA1OTU0MzM2MH0.mdHOJ_HoKARetqHF73e-UVqpg4SS37CuoSORUtSHtL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create site_settings table if it doesn't exist
const initializeDatabase = async () => {
  // Check if site_settings table exists
  const { error: checkError } = await supabase
    .from('site_settings')
    .select('*')
    .limit(1)
    .catch(() => ({ error: { message: 'Table does not exist' } }));

  if (checkError) {
    console.log('Attempting to create site_settings table...');
    
    // Create the site_settings table using SQL
    const { error: createError } = await supabase.rpc('create_site_settings_table');
    
    if (createError) {
      console.error('Error creating site_settings table:', createError);
    } else {
      console.log('Successfully created site_settings table');
    }
  }
};

// Initialize the database when the app loads
initializeDatabase();
